=== malinastanciu/proiect-xis/laborator_analize.dtd
<!ELEMENT laborator_medical (laborator, categorii, pacienti, medici)>
    <!ELEMENT laborator (nume_laborator, contact)>
        <!ELEMENT nume_laborator (#PCDATA)>
        <!ELEMENT contact (telefon_laborator, email_laborator)>
            <!ELEMENT telefon_laborator (#PCDATA)>
            <!ELEMENT email_laborator (#PCDATA)>
    <!ELEMENT categorii (categorie+)>
        <!ELEMENT categorie (analize)>
        <!ATTLIST categorie nume_categorie CDATA #REQUIRED>
            <!ELEMENT analize (analiza+)>
                <!ELEMENT analiza (nume_analiza, descriere, indicatii, interpretare, pret)>
                    <!ELEMENT nume_analiza (#PCDATA)>
                    <!ELEMENT descriere (#PCDATA)>
                    <!ELEMENT indicatii (#PCDATA)>
                    <!ELEMENT interpretare (nivel_scazut, nivel_ridicat)>
                        <!ELEMENT nivel_scazut (valoare_ns, boala_ns)>
                            <!ELEMENT valoare_ns (#PCDATA)>
                            <!ELEMENT boala_ns (#PCDATA)>
                        <!ELEMENT nivel_ridicat (valoare_nr, boala_nr)>
                            <!ELEMENT valoare_nr (#PCDATA)>
                            <!ELEMENT boala_nr (#PCDATA)>
                    <!ELEMENT pret (#PCDATA)>
    <!ELEMENT pacienti (pacient+)>
        <!ELEMENT pacient (nume_pacient, prenume_pacient, cnp, varsta_pacient, telefon_pacient, sex, email, istoric_medical)>
            <!ELEMENT nume_pacient (#PCDATA)>
            <!ELEMENT prenume_pacient (#PCDATA)>
            <!ELEMENT cnp (#PCDATA)>
            <!ELEMENT varsta_pacient (#PCDATA)>
            <!ELEMENT telefon_pacient (#PCDATA)>
            <!ELEMENT sex (#PCDATA)>
            <!ELEMENT email (#PCDATA)>
            <!ELEMENT istoric_medical (vizita+)>
                <!ELEMENT vizita (analiza_pacient, data_efectuare, rezultat)>
                    <!ELEMENT analiza_pacient (#PCDATA)>
                    <!ELEMENT data_efectuare (#PCDATA)>
                    <!ELEMENT rezultat (#PCDATA)>
    <!ELEMENT medici (medic+)>
        <!ELEMENT medic (nume_medic, prenume_medic, varsta_medic, vechime, specializare+)>
            <!ELEMENT nume_medic (#PCDATA)>
            <!ELEMENT prenume_medic (#PCDATA)>
            <!ELEMENT varsta_medic (#PCDATA)>
            <!ELEMENT vechime (#PCDATA)> 
            <!ELEMENT specializare (#PCDATA)>

=== malinastanciu/proiect-xis/laborator_analize.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- <!DOCTYPE laborator_medical SYSTEM "laborator_analize.dtd"> -->
<?xml-stylesheet type="text/xsl" href="laborator_analize.xsl"?>

<!-- Gestiunea analizelor pacientilor intr-un laborator medical -->
<laborator_medical xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="laborator_analize.xsd">
    <laborator>
        <nume_laborator>Live Together</nume_laborator>
        <contact>
            <telefon_laborator>0733910940</telefon_laborator>
            <email_laborator>office@live-together.ro</email_laborator>
        </contact>
    </laborator>


    <categorii>
        <categorie nume_categorie="Biochimie">
            <analize>
                <analiza>
                    <nume_analiza>Acid uric urinar</nume_analiza>
                    <descriere>Acidul uric este produsul final al metabolismului purinelor (componente importante ale acizilor nucleici si coenzimelor care pot fi sintetizate in corp sau pot fi obtinute prin consumul unor alimente).</descriere>
                    <indicatii>Determinarea acidului uric urinar este indicata pentru: diagnosticarea  calculilor renali, determinare cauzei litiazei renale recurente, monitorizarea persoanelor cu guta</indicatii>
                    <interpretare>
                        <nivel_scazut>
                            <valoare_ns>10</valoare_ns>
                            <boala_ns>Afectiuni renale cornice, Xantinurie, Intoxicatie cu plumb</boala_ns>
                        </nivel_scazut>
                        <nivel_ridicat>
                            <valoare_nr>39</valoare_nr>
                            <boala_nr>Leucemie, Nefrolitiaza, Hepatie virala, Siclemie</boala_nr>
                        </nivel_ridicat>
                    </interpretare>
                    <pret>32</pret>
                </analiza>

                <analiza>
                    <nume_analiza>Profil lipidic (colesterol, colest HDL, LDL, trigliceride)</nume_analiza>
                    <descriere>Trigliceridele sunt compusi lipidici formati din glicerol esterificat cu 3 catene  de acizi grasi. Se gasesc in majoritatea grasimilor si uleiurilor vegetale si animale. Trigliceridele din tesutul adipos reprezinta cel mai important depozit de rezerve energetice ale organismului. Valori ridicate ale trigliceridelor, reprezinta un factor de risc pentru aparitia diabetului sau patologii pancreatice. Hipertrigliceridemia este un factor de risc pentru boala arterelor coronare in special cand HDL scazut este prezent. Profilul standard de lipide consta in masurarea: trigliceridelor, colesterolului total, HDL colesterol, LDL colesterol</descriere>
                    <indicatii>Testarea profilului lipidic se recomanda in urmatoarele situatii: identificarea hiperlipemiilor, evaluarea riscului de aterscleroza, toti adultii peste 20 ani o data la 5 ani, barbati cu varsta > 35 ani cu risc crescut de boala coronariana, femeie cu varsta >45 ani cu risc crescut de boala coronariana.</indicatii>
                    <interpretare>
                        <nivel_scazut>
                            <valoare_ns>20</valoare_ns>
                            <boala_ns>Malnutritie, Malabsorbtie, Hipertiroidism, BROC</boala_ns>
                        </nivel_scazut>
                        <nivel_ridicat>
                            <valoare_nr>200</valoare_nr>
                            <boala_nr>Guta, Pancreatita, Boli renale, Diabet zaharat, Anorexie nervoasa, Alcoolism</boala_nr>
                        </nivel_ridicat>
                    </interpretare>
                    <pret>66</pret>
                </analiza>
            </analize>
        </categorie>

        <categorie nume_categorie="Biologie moleculara">
            <analize>
                <analiza>
                    <nume_analiza>HIV/1 ARN (Cantitativ)</nume_analiza>
                    <descriere>Virusul imunodeficientei umane (HIV) este virusul care provoaca sindromul imunodeficientei dobandite (SIDA). Acest test masoara cantitatea (incarcatura virala) materialului genetic din sange si raporteaza cate copii ale virusului sunt prezente. Cand o persoana este initial infectata cu HIV, virusul se replica, iar principalul obiectiv sunt celulele CD4 (celule albe din sange care lupta impotriva infectiilor). Virusul intra in celule si le foloseste pentru a se replica si raspandi in tot corpul. Se deplaseaza in ganglionii limfatici, splina si in alte parti ale corpului.</descriere>
                    <indicatii>Monitorizarea evolutiei bolii (in prezenta sau in absenta terapiei antiretrovirale) , diagnosticul infectiei la nou-nascuti, evaluarea eficacitatii diferitelor tratamente antivirale</indicatii>
                    <interpretare>
                        <nivel_scazut>
                            <valoare_ns>0</valoare_ns>
                            <boala_ns>Lipsa virusului HIV</boala_ns>
                        </nivel_scazut>
                        <nivel_ridicat>
                            <valoare_nr>1</valoare_nr>
                            <boala_nr>Existenta virusului HIV in organism</boala_nr>
                        </nivel_ridicat>
                    </interpretare>
                    <pret>2987</pret>
                </analiza>
        </analize>
        </categorie>

        <categorie nume_categorie="Alergologie si imunologie">
            <analize>
                <analiza>
                    <nume_analiza>Imunoglobulina A</nume_analiza>
                    <descriere>Imunoglobulinele sunt glicoproteine produse de celulele plasmatice ca raspuns la un antigen. Sunt impartite in 5 clase dupa cum urmeaza: IgG - lanturi grele γ, IgM - lanturi grele μ, IgA - lanturi grele U+03b1, IgD-lanturi grele U+03b4, IgE - lanturi grele U+03b5. Roluri: IgG - aparare antivirala,antibacteriana si contra toxinelor bacteriene, IgA - apararea mucoaselor, IgM - aparare antibacteriana, IgE - in anafilaxie si aparare antiparazitara, IgD - intra in alcatuirea receptorilor pentru antigen ai limfocitelor B</descriere>
                    <indicatii>Diagnosticul si monitorizarea gamapatiilor monoclonale, Diagnosticul si monitorizarea deficitelor sistemului imunitar</indicatii>
                    <interpretare>
                        <nivel_scazut>
                            <valoare_ns>2</valoare_ns>
                            <boala_ns>Ataxietelengiectazie, Boala sinopulmonara cronica, Deficit congenital</boala_ns>
                        </nivel_scazut>
                        <nivel_ridicat>
                            <valoare_nr>4</valoare_nr>
                            <boala_nr>Mielom IgA, Ciroza hepatica, Icter obstructiv, Alcoolism, Infectii subacute si cronice, Sindrom Wiskott-Aldrich</boala_nr>
                        </nivel_ridicat>
                    </interpretare>
                    <pret>46</pret>
                </analiza>

                <analiza>
                    <nume_analiza>Imunoglobulina G</nume_analiza>
                    <descriere>Acest test masoara cantitatea de imunoglobuline G din sange si in anumite situatii din lichidul cefalorahidian sau din saliva. Exista numeroase boli si afectiuni care pot cauza cresterea sau scaderea productiei de imunoglobuline serice. Imunoglobulina G (IgG) reprezinta aproximativ 70-80% din imunoglobulinele din sange. Anticorpii IgG constituie baza de protectie pe termen lung impotriva microorganismelor. Anticorpii IgG specifici sunt produsi in timpul unei infectii sau la expunerea initial, avand evolutie crescatoare timp de cateva saptamani de la debut, scaznd apoi si stabilizandu-se. Anticorpii IgG ai mamei ofera fatului protectie in timpul sarcinii si in timpul primelor sale luni de viata</descriere>
                    <indicatii>Recomandari pentru determinarea IgG: evaluarea imunitatii umorale, diagnosticul de mielom IgG, monitorizarea terapiei in mielomul IgG, estimarea riscului de infectii la pacientii cu limfoame.</indicatii>
                    <interpretare>
                        <nivel_scazut>
                            <valoare_ns>5</valoare_ns>
                            <boala_ns>Mielom non-IgG, Sindroame cu pierdere de protein, Sarcina, Macroglobulinemie, Aplazie limfoida, Leucemie lifatica cronica, Deficient selective de IgG, Agamaglobulinemie</boala_ns>
                        </nivel_scazut>
                        <nivel_ridicat>
                            <valoare_nr>8</valoare_nr>
                            <boala_nr>Afectiuni hepatice cronice, Sarcoidoza, Boli autoimmune, Malnutritie severa, Parazitoze,  Hiperimunizare, Disproteinemie, Mielom IgG</boala_nr>
                        </nivel_ridicat>
                    </interpretare>
                    <pret>98</pret>
                </analiza>

                <analiza>
                    <nume_analiza>Coenzima Q10</nume_analiza>
                    <descriere>Coenzima Q10 (CoQ10) este un cofactor esential in lantul respirator mitocondrial, responsabil pentru fosforilarea oxidativa, unde functioneaza ca purtator de electroni si actioneaza ca antioxidant. CoQ10 se gaseste in toate membranele celulare si este transportata de catre lipoproteine in circulatie.</descriere>
                    <indicatii>Diagnosticul deficientei de CoQ10 in afectiunile mitocondriale, Monitorizarea pacientilor care primesc tratament cu statine, Monitorizarea statusului CoQ10 in cursul tratamentului unor boli degenerative, precum boala Parkinson si boala Alzheimer</indicatii>
                    <interpretare>
                        <nivel_scazut>
                            <valoare_ns>0.5</valoare_ns>
                            <boala_ns>Encefalomiopatie</boala_ns>
                        </nivel_scazut>
                        <nivel_ridicat>
                            <valoare_nr>1.48</valoare_nr>
